#===============================================================================================#
#                                                                                               #
#                                     ::::::::  ::::::::::                                      #
#                                     :+:    :+: :+:                                            #
#                  +:+:+:+:+:+:+      +:+        +:+             +:+:+:+:+:+:+                  #
#     +#++:++#++:++                   +#+        :#::+::#                     +#++:++#++:++     #
#                  +#+#+#+#+#+#+      +#+        +#+             +#+#+#+#+#+#+                  #
#                                     #+#    #+# #+#                                            #
#                                     ########  ###                                             #
#                                                                                               #
#===============================================================================================#

#===============================================================================================#
#                                                                                               #
#                             (c) Efnilite 2021-2022. Do not distribute!                        #
#                                                                                               #
#===============================================================================================#

# If verbosing is enabled, useful for developers.
verbose: false

# If the update checker is enabled.
# !! Highly recommended to be turned on !!
updater: true