#===============================================================================================#
#                                                                                               #
#                                     ::::::::  ::::::::::                                      #
#                                     :+:    :+: :+:                                            #
#                  +:+:+:+:+:+:+      +:+        +:+             +:+:+:+:+:+:+                  #
#     +#++:++#++:++                   +#+        :#::+::#                     +#++:++#++:++     #
#                  +#+#+#+#+#+#+      +#+        +#+             +#+#+#+#+#+#+                  #
#                                     #+#    #+# #+#                                            #
#                                     ########  ###                                             #
#                                                                                               #
#===============================================================================================#

#===============================================================================================#
#                                                                                               #
#                             (c) Efnilite 2021-2022. Do not distribute!                        #
#                                                                                               #
#===============================================================================================#

# -= Auto updater =-.
# Whether the auto updater should automatically download new versions when it has found one.
# It is highly recommended to keep this enabled!
auto-updater: true