name: CommandFactory
author: Efnilite
description: Add commands within seconds
main: dev.efnilite.commandfactory.CommandFactory
version: 1.1.2
api-version: 1.16
depend: [vilib]
commands:
    commandfactory:
        aliases: [cf, commandf, factory]
        description: The main command of CommandFactory