name: CommandFactory
author: Efnilite
description: Easily manage commands. Add one within seconds.
main: dev.efnilite.commandfactory.CommandFactory
version: 1.1.4
api-version: 1.16
depend: [vilib]
commands:
    commandfactory:
        aliases: [cf, commandf, factory]
        description: The main command of CommandFactory